on:
  push:
    branches:
      - ActionTest


jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: create pull request
        run: gh pr create -B main -H ActionTest --reviewer 'toeppen' --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}